name: 💡 General Feature Request
description: Have a new idea/feature for this project? Would love to hear it!
title: "[FEATURE] <what do you have to add>"
labels:
  [
    "enhancement",
  ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you checked if this issue has been raised before?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true


  - type: dropdown
    attributes:
      label: Are you willing to work on this issue 
      options:
        - "Yes I am willing to submit a PR!"

  - type: markdown
    attributes:
      value: |
        Follow me on Twitter [here](https://twitter.com/kunalshah017)
