name: 🔒 Vulnerability
description: Report a security vulnerability to help improve the project.
title: "[VULNERABILITY] <brief vulnerability description>"
labels:
  [
    "security"
  ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the vulnerability you have found
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please provide steps to reproduce the vulnerability
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Please describe the potential impact of this vulnerability
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Fix
      description: Please provide any suggestions you may have for fixing the vulnerability
    validations:
      required: false
